// Renders the real pixel shader offline and reads the pixels back.
//
// Everything else in the pipeline is verified by eye against MANUAL-TESTS.md, which is fine
// for "does this look like a CRT" but useless for the two claims that are actually mechanical:
// that a disabled module changes nothing at all (AT-010, FILTERS-AND-EFFECTS.md section 5), and
// that the aspect-fit mapping puts the source where it belongs. Both are pixel facts, so this
// measures them instead of asking someone to squint.
//
// The device is created without a swap chain and the result is copied to a staging texture -
// a readback, which the hot path forbids (ADR-0005) and a test is entitled to.

#include <Windows.h>

#include <d3d11.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iterator>
#include <vector>

#include "core/PresetRepository.h"
#include "core/Settings.h"
#include "graphics/RenderResources.h"

// Generated by cmake/CompileShaders.cmake at build time, the same headers the application
// links: this tests the shipped bytecode, not a recompilation of it.
#include "shaders/OverlayDeskPS.h"
#include "shaders/OverlayDeskVS.h"

using namespace overlaydesk;

namespace {

int g_failures = 0;

void Check(bool condition, const char* expression, int line) {
    if (!condition) {
        ++g_failures;
        std::printf("FAIL (line %d): %s\n", line, expression);
    }
}

#define CHECK(expr) Check((expr), #expr, __LINE__)

struct Rgba {
    uint8_t b = 0;
    uint8_t g = 0;
    uint8_t r = 0;
    uint8_t a = 0;
};

// One rendered frame: BGRA8, row-major, `width` pixels per row.
struct Image {
    uint32_t width = 0;
    uint32_t height = 0;
    std::vector<Rgba> pixels;

    const Rgba& At(uint32_t x, uint32_t y) const { return pixels[y * width + x]; }
};

// --- Device ---------------------------------------------------------------------------------

class Harness {
public:
    // False when no Direct3D 11 device of any kind can be created, which is a skip and not a
    // failure: a build agent without a GPU still has to be able to run the rest of the suite.
    bool Create() {
        const D3D_FEATURE_LEVEL levels[] = {D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0,
                                            D3D_FEATURE_LEVEL_10_1, D3D_FEATURE_LEVEL_10_0};

        // WARP first: it is deterministic, always present, and fast enough for a handful of
        // 400x400 frames. Hardware would make the numbers depend on the driver.
        HRESULT hr = ::D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_WARP, nullptr, 0, levels,
                                         ARRAYSIZE(levels), D3D11_SDK_VERSION, &m_device, nullptr,
                                         &m_context);
        if (FAILED(hr)) {
            hr = ::D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0, levels,
                                     ARRAYSIZE(levels), D3D11_SDK_VERSION, &m_device, nullptr,
                                     &m_context);
        }
        if (FAILED(hr)) {
            return false;
        }

        if (FAILED(m_device->CreateVertexShader(g_OverlayDeskVS, sizeof(g_OverlayDeskVS), nullptr,
                                                &m_vs)) ||
            FAILED(m_device->CreatePixelShader(g_OverlayDeskPS, sizeof(g_OverlayDeskPS), nullptr,
                                               &m_ps))) {
            return false;
        }

        D3D11_BUFFER_DESC cb{};
        cb.ByteWidth = sizeof(ShaderConstants);
        cb.Usage = D3D11_USAGE_DYNAMIC;
        cb.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        cb.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        if (FAILED(m_device->CreateBuffer(&cb, nullptr, &m_constants))) {
            return false;
        }

        D3D11_SAMPLER_DESC sampler{};
        sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sampler.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampler.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampler.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampler.MaxLOD = D3D11_FLOAT32_MAX;
        return SUCCEEDED(m_device->CreateSamplerState(&sampler, &m_sampler));
    }

    ~Harness() {
        Release(m_sampler);
        Release(m_constants);
        Release(m_ps);
        Release(m_vs);
        Release(m_context);
        Release(m_device);
    }

    // Uploads `source` as the captured frame and renders one frame of `settings` at
    // outWidth x outHeight.
    Image Render(const AppSettings& settings, const Image& source, uint32_t outWidth,
                 uint32_t outHeight, float time = 0.0f) {
        Image result;

        ID3D11Texture2D* sourceTexture = nullptr;
        ID3D11ShaderResourceView* sourceView = nullptr;
        ID3D11Texture2D* target = nullptr;
        ID3D11RenderTargetView* targetView = nullptr;
        ID3D11Texture2D* staging = nullptr;

        D3D11_TEXTURE2D_DESC desc{};
        desc.Width = source.width;
        desc.Height = source.height;
        desc.MipLevels = 1;
        desc.ArraySize = 1;
        desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
        desc.SampleDesc.Count = 1;
        desc.Usage = D3D11_USAGE_IMMUTABLE;
        desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;

        D3D11_SUBRESOURCE_DATA initial{};
        initial.pSysMem = source.pixels.data();
        initial.SysMemPitch = source.width * static_cast<UINT>(sizeof(Rgba));

        if (FAILED(m_device->CreateTexture2D(&desc, &initial, &sourceTexture)) ||
            FAILED(m_device->CreateShaderResourceView(sourceTexture, nullptr, &sourceView))) {
            Release(sourceView);
            Release(sourceTexture);
            return result;
        }

        D3D11_TEXTURE2D_DESC rt{};
        rt.Width = outWidth;
        rt.Height = outHeight;
        rt.MipLevels = 1;
        rt.ArraySize = 1;
        rt.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
        rt.SampleDesc.Count = 1;
        rt.Usage = D3D11_USAGE_DEFAULT;
        rt.BindFlags = D3D11_BIND_RENDER_TARGET;

        D3D11_TEXTURE2D_DESC read = rt;
        read.Usage = D3D11_USAGE_STAGING;
        read.BindFlags = 0;
        read.CPUAccessFlags = D3D11_CPU_ACCESS_READ;

        if (FAILED(m_device->CreateTexture2D(&rt, nullptr, &target)) ||
            FAILED(m_device->CreateRenderTargetView(target, nullptr, &targetView)) ||
            FAILED(m_device->CreateTexture2D(&read, nullptr, &staging))) {
            Release(staging);
            Release(targetView);
            Release(target);
            Release(sourceView);
            Release(sourceTexture);
            return result;
        }

        SourceGeometry geometry;
        geometry.contentWidth = source.width;
        geometry.contentHeight = source.height;
        geometry.textureWidth = source.width;
        geometry.textureHeight = source.height;

        const ShaderConstants constants =
            BuildShaderConstants(settings, outWidth, outHeight, geometry, time,
                                 /*hasSource=*/true, /*editMode=*/false, 0.0f);

        D3D11_MAPPED_SUBRESOURCE mapped{};
        if (SUCCEEDED(m_context->Map(m_constants, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
            std::memcpy(mapped.pData, &constants, sizeof(constants));
            m_context->Unmap(m_constants, 0);
        }

        const float clear[4] = {0.0f, 0.0f, 0.0f, 0.0f};
        m_context->ClearRenderTargetView(targetView, clear);
        m_context->OMSetRenderTargets(1, &targetView, nullptr);

        D3D11_VIEWPORT viewport{};
        viewport.Width = static_cast<float>(outWidth);
        viewport.Height = static_cast<float>(outHeight);
        viewport.MaxDepth = 1.0f;
        m_context->RSSetViewports(1, &viewport);

        m_context->IASetInputLayout(nullptr);
        m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        m_context->VSSetShader(m_vs, nullptr, 0);
        m_context->PSSetShader(m_ps, nullptr, 0);
        m_context->PSSetConstantBuffers(0, 1, &m_constants);
        m_context->PSSetSamplers(0, 1, &m_sampler);
        m_context->PSSetShaderResources(0, 1, &sourceView);
        m_context->Draw(3, 0);

        ID3D11ShaderResourceView* none = nullptr;
        m_context->PSSetShaderResources(0, 1, &none);
        m_context->OMSetRenderTargets(0, nullptr, nullptr);

        m_context->CopyResource(staging, target);

        if (SUCCEEDED(m_context->Map(staging, 0, D3D11_MAP_READ, 0, &mapped))) {
            result.width = outWidth;
            result.height = outHeight;
            result.pixels.resize(static_cast<size_t>(outWidth) * outHeight);
            const uint8_t* row = static_cast<const uint8_t*>(mapped.pData);
            for (uint32_t y = 0; y < outHeight; ++y) {
                std::memcpy(&result.pixels[static_cast<size_t>(y) * outWidth], row,
                            static_cast<size_t>(outWidth) * sizeof(Rgba));
                row += mapped.RowPitch;
            }
            m_context->Unmap(staging, 0);
        }

        Release(staging);
        Release(targetView);
        Release(target);
        Release(sourceView);
        Release(sourceTexture);
        return result;
    }

private:
    template <typename T>
    static void Release(T*& value) {
        if (value != nullptr) {
            value->Release();
            value = nullptr;
        }
    }

    ID3D11Device* m_device = nullptr;
    ID3D11DeviceContext* m_context = nullptr;
    ID3D11VertexShader* m_vs = nullptr;
    ID3D11PixelShader* m_ps = nullptr;
    ID3D11Buffer* m_constants = nullptr;
    ID3D11SamplerState* m_sampler = nullptr;
};

// --- Fixtures -------------------------------------------------------------------------------

// A hard vertical edge at `edgeX` of the width, dark on the left and bright on the right.
// A single sharp feature is what makes a geometric change measurable: find the edge, compare
// where it landed.
Image MakeEdgeSource(uint32_t width, uint32_t height, float edgeX) {
    Image image;
    image.width = width;
    image.height = height;
    image.pixels.resize(static_cast<size_t>(width) * height);

    const uint32_t boundary = static_cast<uint32_t>(edgeX * static_cast<float>(width));
    for (uint32_t y = 0; y < height; ++y) {
        for (uint32_t x = 0; x < width; ++x) {
            const uint8_t value = x < boundary ? 20 : 230;
            image.pixels[static_cast<size_t>(y) * width + x] = Rgba{value, value, value, 255};
        }
    }
    return image;
}

// A lens distortion chart: straight lines are what make barrel and pincushion legible, and a
// circle shows the radial component at a glance.
Image MakeGridSource(uint32_t width, uint32_t height) {
    Image image;
    image.width = width;
    image.height = height;
    image.pixels.assign(static_cast<size_t>(width) * height, Rgba{28, 26, 24, 255});

    const auto plot = [&image](int x, int y, Rgba colour) {
        if (x >= 0 && y >= 0 && x < static_cast<int>(image.width) &&
            y < static_cast<int>(image.height)) {
            image.pixels[static_cast<size_t>(y) * image.width + x] = colour;
        }
    };

    constexpr uint32_t kStep = 32;
    const Rgba grid{210, 210, 210, 255};
    const Rgba axis{90, 200, 255, 255};

    for (uint32_t y = 0; y < height; ++y) {
        for (uint32_t x = 0; x < width; ++x) {
            const bool onVertical = (x % kStep) == 0;
            const bool onHorizontal = (y % kStep) == 0;
            if (onVertical || onHorizontal) {
                plot(static_cast<int>(x), static_cast<int>(y), grid);
            }
        }
    }

    // Centre cross, in a colour the grid does not use, so the middle is unmistakable.
    for (uint32_t x = 0; x < width; ++x) {
        plot(static_cast<int>(x), static_cast<int>(height / 2), axis);
    }
    for (uint32_t y = 0; y < height; ++y) {
        plot(static_cast<int>(width / 2), static_cast<int>(y), axis);
    }

    // A circle at 40% of the half-height: perfectly round in the source, so any radial
    // distortion shows up as it swelling or shrinking.
    const float cx = static_cast<float>(width) * 0.5f;
    const float cy = static_cast<float>(height) * 0.5f;
    const float radius = static_cast<float>(height) * 0.40f;
    const Rgba ring{120, 255, 160, 255};
    for (int degrees = 0; degrees < 3600; ++degrees) {
        const float angle = static_cast<float>(degrees) * 0.1f * 3.14159265f / 180.0f;
        for (int thickness = 0; thickness < 2; ++thickness) {
            const float r = radius + static_cast<float>(thickness);
            plot(static_cast<int>(cx + std::cos(angle) * r),
                 static_cast<int>(cy + std::sin(angle) * r), ring);
        }
    }

    // Corner blocks: the anchoring rule says these stay put at every amount, so they are the
    // reference the rest of the frame moves against.
    const Rgba corner{255, 120, 90, 255};
    for (uint32_t y = 0; y < 10; ++y) {
        for (uint32_t x = 0; x < 10; ++x) {
            plot(static_cast<int>(x), static_cast<int>(y), corner);
            plot(static_cast<int>(width - 1 - x), static_cast<int>(y), corner);
            plot(static_cast<int>(x), static_cast<int>(height - 1 - y), corner);
            plot(static_cast<int>(width - 1 - x), static_cast<int>(height - 1 - y), corner);
        }
    }

    return image;
}

// 24-bit bottom-up BMP, the format that needs no library. The frame is composited over `bg`
// first: the output is premultiplied alpha, so a letterbox bar is all zeroes and would be
// indistinguishable from black without something behind it.
// Reads a 24- or 32-bit uncompressed BMP so a look can be judged against real footage instead
// of against the synthetic grid. Only the shapes WriteBmp itself emits, plus the 32-bit variant
// most tools save: this exists to close the loop on --write-presets, not to be an image library.
bool ReadBmp(const char* path, Image& out) {
    bool ok = false;

    std::FILE* file = nullptr;
    if (fopen_s(&file, path, "rb") == 0 && file != nullptr) {
        uint8_t header[54]{};
        if (std::fread(header, 1, sizeof(header), file) == sizeof(header) && header[0] == 'B' &&
            header[1] == 'M') {
            const auto u32 = [&header](size_t at) {
                return static_cast<uint32_t>(header[at]) |
                       (static_cast<uint32_t>(header[at + 1]) << 8) |
                       (static_cast<uint32_t>(header[at + 2]) << 16) |
                       (static_cast<uint32_t>(header[at + 3]) << 24);
            };

            const uint32_t dataOffset = u32(10);
            const uint32_t width = u32(18);
            const int32_t signedHeight = static_cast<int32_t>(u32(22));
            const uint32_t height = static_cast<uint32_t>(std::abs(signedHeight));
            const uint32_t bpp =
                static_cast<uint32_t>(header[28]) | (static_cast<uint32_t>(header[29]) << 8);
            const uint32_t compression = u32(30);

            if (width > 0 && height > 0 && (bpp == 24 || bpp == 32) && compression == 0 &&
                std::fseek(file, static_cast<long>(dataOffset), SEEK_SET) == 0) {
                const uint32_t bytesPerPixel = bpp / 8u;
                const uint32_t rowBytes = ((width * bytesPerPixel) + 3u) & ~3u;
                std::vector<uint8_t> row(rowBytes);

                out.width = width;
                out.height = height;
                out.pixels.assign(static_cast<size_t>(width) * height, Rgba{0, 0, 0, 255});

                ok = true;
                for (uint32_t i = 0; i < height && ok; ++i) {
                    // A positive height means the rows are stored bottom-up.
                    const uint32_t y = signedHeight > 0 ? (height - 1u - i) : i;
                    ok = std::fread(row.data(), 1, rowBytes, file) == rowBytes;
                    for (uint32_t x = 0; x < width && ok; ++x) {
                        Rgba& pixel = out.pixels[static_cast<size_t>(y) * width + x];
                        pixel.b = row[x * bytesPerPixel + 0];
                        pixel.g = row[x * bytesPerPixel + 1];
                        pixel.r = row[x * bytesPerPixel + 2];
                        pixel.a = 255;
                    }
                }
            }
        }
        std::fclose(file);
    }

    if (!ok) {
        std::printf("Could not read '%s' as a 24/32-bit uncompressed BMP.\n", path);
    }
    return ok;
}

bool WriteBmp(const char* path, const Image& image, Rgba background) {
    std::FILE* file = nullptr;
    if (fopen_s(&file, path, "wb") != 0 || file == nullptr) {
        return false;
    }

    const uint32_t rowBytes = ((image.width * 3u) + 3u) & ~3u;
    const uint32_t pixelBytes = rowBytes * image.height;
    const uint32_t headerBytes = 14u + 40u;

    const auto put16 = [file](uint16_t value) { std::fwrite(&value, 2, 1, file); };
    const auto put32 = [file](uint32_t value) { std::fwrite(&value, 4, 1, file); };

    std::fwrite("BM", 1, 2, file);
    put32(headerBytes + pixelBytes);
    put32(0);
    put32(headerBytes);

    put32(40);
    put32(image.width);
    put32(image.height);
    put16(1);
    put16(24);
    put32(0);
    put32(pixelBytes);
    put32(2835);
    put32(2835);
    put32(0);
    put32(0);

    std::vector<uint8_t> row(rowBytes, 0);
    for (uint32_t y = 0; y < image.height; ++y) {
        const uint32_t sourceRow = image.height - 1 - y;  // BMP is bottom-up
        for (uint32_t x = 0; x < image.width; ++x) {
            const Rgba& p = image.At(x, sourceRow);
            const uint32_t inverse = 255u - p.a;
            // Premultiplied source over an opaque background.
            row[x * 3 + 0] = static_cast<uint8_t>(p.b + (background.b * inverse) / 255u);
            row[x * 3 + 1] = static_cast<uint8_t>(p.g + (background.g * inverse) / 255u);
            row[x * 3 + 2] = static_cast<uint8_t>(p.r + (background.r * inverse) / 255u);
        }
        std::fwrite(row.data(), 1, rowBytes, file);
    }

    std::fclose(file);
    return true;
}

size_t CountDifferences(const Image& a, const Image& b) {
    size_t different = 0;
    if (a.width != b.width || a.height != b.height) {
        return a.pixels.size() + b.pixels.size();
    }
    for (size_t i = 0; i < a.pixels.size(); ++i) {
        const Rgba& p = a.pixels[i];
        const Rgba& q = b.pixels[i];
        if (p.r != q.r || p.g != q.g || p.b != q.b || p.a != q.a) {
            ++different;
        }
    }
    return different;
}

// The x of the first pixel on `row` at least as bright as the midpoint, i.e. where the source's
// vertical edge ended up on screen.
uint32_t FindEdge(const Image& image, uint32_t row) {
    uint32_t x = image.width;
    for (uint32_t i = 0; i < image.width; ++i) {
        if (image.At(i, row).g >= 125) {
            x = i;
            break;
        }
    }
    return x;
}

// --- Tests ----------------------------------------------------------------------------------

// AT-010 / FILTERS-AND-EFFECTS.md section 5: a module that is off must not alter one pixel,
// even with every one of its parameters pushed far off its default. Values are dialled in
// first precisely so a stage that ignored its enable bit would show up here.
void TestDisabledModulesAreFree(Harness& harness) {
    const Image source = MakeEdgeSource(160, 120, 0.25f);
    constexpr uint32_t kOut = 400;

    const AppSettings neutral;
    const Image baseline = harness.Render(neutral, source, kOut, kOut);
    CHECK(baseline.width == kOut);
    if (baseline.pixels.empty()) {
        return;
    }

    struct Case {
        const char* name;
        void (*arrange)(AppSettings&);
    };

    const Case cases[] = {
        {"distortion",
         [](AppSettings& s) { s.filters.distortion.amount = 1.0f; }},
        {"vignette",
         [](AppSettings& s) { s.filters.vignette.intensity = 1.0f; s.filters.vignette.size = 0.1f; }},
        {"scanlines",
         [](AppSettings& s) { s.filters.scanlines.intensity = 1.0f;
                              s.filters.scanlines.spacing = 3.0f;
                              s.filters.scanlines.beamWidth = 1.0f;
                              s.filters.scanlines.interlace = 1.0f; }},
        {"chromaticAberration",
         [](AppSettings& s) { s.filters.chromaticAberration.intensity = 1.0f; }},
        {"colorCorrection",
         [](AppSettings& s) { s.filters.colorCorrection.saturation = 0.0f;
                              s.filters.colorCorrection.posterize = 1.0f; }},
        {"scope",
         [](AppSettings& s) { s.filters.scope.size = 0.2f; s.filters.scope.magnification = 3.0f; }},
        {"bloom",
         [](AppSettings& s) { s.filters.bloom.intensity = 1.0f; s.filters.bloom.threshold = 0.0f;
                              s.filters.bloom.radius = 1.0f;
                              s.filters.bloom.tint[0] = 1.0f;
                              s.filters.bloom.tint[1] = 0.2f;
                              s.filters.bloom.tint[2] = 0.0f; }},
        {"falseColour",
         [](AppSettings& s) { s.filters.falseColour.intensity = 1.0f;
                              s.filters.falseColour.palette = FalseColourPalette::Ironbow; }},
        {"edgeGlow",
         [](AppSettings& s) { s.filters.edgeGlow.intensity = 1.0f; s.filters.edgeGlow.width = 1.0f; }},
        {"lensSoftness",
         [](AppSettings& s) { s.filters.lensSoftness.intensity = 1.0f;
                              s.filters.lensSoftness.center = 0.0f; }},
        {"sharpen",
         [](AppSettings& s) { s.filters.sharpen.intensity = 1.0f;
                              s.filters.sharpen.radius = 1.0f; }},
        {"lensDirt",
         [](AppSettings& s) { s.filters.lensDirt.intensity = 1.0f; s.filters.lensDirt.density = 1.0f; }},
        {"glitch",
         [](AppSettings& s) { s.effects.glitch.intensity = 1.0f; s.effects.glitch.frequency = 1.0f; }},
        {"noise",
         [](AppSettings& s) { s.effects.noise.intensity = 1.0f; }},
        {"flicker",
         [](AppSettings& s) { s.effects.flicker.intensity = 1.0f; }},
        {"jitter",
         [](AppSettings& s) { s.effects.jitter.intensity = 1.0f; }},
        {"shimmer",
         [](AppSettings& s) { s.effects.shimmer.intensity = 1.0f; }},
        {"rollingShutter",
         [](AppSettings& s) { s.effects.rollingShutter.intensity = 1.0f; }},
        {"scanSweep",
         [](AppSettings& s) { s.effects.scanSweep.intensity = 1.0f; s.effects.scanSweep.width = 1.0f; }},
    };

    for (const Case& item : cases) {
        AppSettings settings;
        item.arrange(settings);

        // A non-zero time so anything driven by g_time would have moved by now.
        const Image rendered = harness.Render(settings, source, kOut, kOut, 3.7f);
        const size_t differences = CountDifferences(baseline, rendered);
        if (differences != 0) {
            std::printf("FAIL: disabled '%s' changed %zu of %zu pixels\n", item.name, differences,
                        baseline.pixels.size());
            ++g_failures;
        }
    }
}

// The aspect-fit mapping. A source far wider than the overlay has to be letterboxed, with the
// bars fully transparent so whatever is underneath shows through (ADR-0006 composes the swap
// chain with premultiplied alpha, so a bar is literally all zeroes).
//
// This is the regression that motivated the harness: the mapping was computed, uploaded and
// never applied, so the source was stretched to fill the overlay and the bars never existed.
void TestAspectFitLetterbox(Harness& harness) {
    // 4:1 content into a square overlay: content occupies the middle quarter of the height.
    const Image source = MakeEdgeSource(256, 64, 0.25f);
    constexpr uint32_t kOut = 400;

    const AppSettings settings;
    const Image rendered = harness.Render(settings, source, kOut, kOut);
    if (rendered.pixels.empty()) {
        CHECK(false);
        return;
    }

    // Rows well inside the top and bottom bars.
    for (const uint32_t row : {2u, 40u, kOut - 41u, kOut - 3u}) {
        const Rgba& bar = rendered.At(kOut / 2, row);
        if (bar.a != 0 || bar.r != 0 || bar.g != 0 || bar.b != 0) {
            std::printf("FAIL: row %u should be a transparent letterbox bar, got rgba(%u,%u,%u,%u)\n",
                        row, bar.r, bar.g, bar.b, bar.a);
            ++g_failures;
        }
    }

    // The middle band is the picture, and it is opaque.
    CHECK(rendered.At(kOut / 2, kOut / 2).a == 255);

    // The content band is a quarter of the height, centred: rows 150..250 of 400.
    CHECK(rendered.At(kOut / 2, 152).a == 255);
    CHECK(rendered.At(kOut / 2, 248).a == 255);
    CHECK(rendered.At(kOut / 2, 145).a == 0);
    CHECK(rendered.At(kOut / 2, 255).a == 0);
}

// A square source in a square overlay fills it completely - the fit must not letterbox when
// there is nothing to letterbox, which is the other half of the mapping being right.
void TestMatchingAspectFillsOverlay(Harness& harness) {
    const Image source = MakeEdgeSource(128, 128, 0.25f);
    constexpr uint32_t kOut = 400;

    const AppSettings settings;
    const Image rendered = harness.Render(settings, source, kOut, kOut);
    if (rendered.pixels.empty()) {
        CHECK(false);
        return;
    }

    CHECK(rendered.At(2, 2).a == 255);
    CHECK(rendered.At(kOut - 3, kOut - 3).a == 255);
    CHECK(rendered.At(kOut / 2, 2).a == 255);
}

// AT-008: the bipolar control. Fisheye magnifies the centre, so a feature to the left of centre
// is pushed further left; anti-fisheye pulls it back towards the centre; and zero is identity.
void TestDistortionMovesTheImage(Harness& harness) {
    const Image source = MakeEdgeSource(128, 128, 0.25f);
    constexpr uint32_t kOut = 400;
    constexpr uint32_t kRow = kOut / 2;

    AppSettings neutral;
    const Image baseline = harness.Render(neutral, source, kOut, kOut);
    if (baseline.pixels.empty()) {
        CHECK(false);
        return;
    }

    const uint32_t restingEdge = FindEdge(baseline, kRow);
    // The source edge is at 25% of the width, so it should land near a quarter across.
    CHECK(restingEdge > 90 && restingEdge < 110);

    AppSettings zero;
    zero.filters.distortion.enabled = true;
    zero.filters.distortion.amount = 0.0f;
    const Image unbent = harness.Render(zero, source, kOut, kOut);
    // Continuity through zero, measured rather than asserted: amount 0 with the module ON has
    // to match the module being off exactly.
    CHECK(CountDifferences(baseline, unbent) == 0);

    AppSettings fisheye;
    fisheye.filters.distortion.enabled = true;
    fisheye.filters.distortion.amount = 1.0f;
    const Image bulged = harness.Render(fisheye, source, kOut, kOut);
    const uint32_t fisheyeEdge = FindEdge(bulged, kRow);

    AppSettings anti;
    anti.filters.distortion.enabled = true;
    anti.filters.distortion.amount = -1.0f;
    const Image pinched = harness.Render(anti, source, kOut, kOut);
    const uint32_t antiEdge = FindEdge(pinched, kRow);

    // Curvature is what actually separates the two halves, and it is the only thing that does.
    // Overall scale does not: since ADR-0010 the anti-fisheye half crops rather than leaving a
    // hole, so it zooms in, and a feature can move the same direction under both halves. What
    // cannot be the same is the bow - a straight vertical line bulges away from the centre
    // under fisheye and towards it under anti-fisheye. Comparing the middle row against a row
    // a quarter of the way down measures exactly that, and is blind to any uniform zoom.
    constexpr uint32_t kOffRow = kOut / 4;

    const int baselineBow =
        static_cast<int>(FindEdge(baseline, kOffRow)) - static_cast<int>(restingEdge);
    const int fisheyeBow =
        static_cast<int>(FindEdge(bulged, kOffRow)) - static_cast<int>(fisheyeEdge);
    const int antiBow =
        static_cast<int>(FindEdge(pinched, kOffRow)) - static_cast<int>(antiEdge);

    std::printf("  distortion: edge at %u resting, %u fisheye, %u anti-fisheye\n", restingEdge,
                fisheyeEdge, antiEdge);
    std::printf("  distortion: bow (quarter row - middle row) %+d resting, %+d fisheye, %+d anti\n",
                baselineBow, fisheyeBow, antiBow);

    // The source edge is straight, so the undistorted render has no bow at all.
    CHECK(baselineBow == 0);

    // The line is left of centre. Fisheye pushes the middle row further left than the quarter
    // row, so the quarter row sits at a larger x: a positive bow. Anti-fisheye does the
    // opposite.
    CHECK(fisheyeBow > 0);
    CHECK(antiBow < 0);

    // And each has to be worth seeing, not a pixel of rounding. The bow is read a quarter of
    // the way down rather than at the corner, where it would be largest, so single digits here
    // are the honest magnitude.
    CHECK(fisheyeBow >= 4);
    CHECK(antiBow <= -4);

    // "Did it move at all" needs a fixture with detail everywhere: with a single edge, most of
    // the frame is flat and a geometric change moves only the pixels near it. The grid has a
    // line every 32 source pixels, so any real displacement shows up in the tens of thousands.
    const Image grid = MakeGridSource(160, 120);
    const Image gridBaseline = harness.Render(neutral, grid, kOut, kOut);

    // Every shape carries its own bipolar behaviour (ADR-0007 section 2), and every one of them
    // still returns to the identity at zero.
    const DistortionShape shapes[] = {DistortionShape::Radial, DistortionShape::Crt,
                                      DistortionShape::Cylindrical, DistortionShape::Vertical,
                                      DistortionShape::Corner};
    const char* names[] = {"radial", "crt", "cylindrical", "vertical", "corner"};

    for (size_t i = 0; i < std::size(shapes); ++i) {
        AppSettings shaped;
        shaped.filters.distortion.enabled = true;
        shaped.filters.distortion.shape = shapes[i];

        shaped.filters.distortion.amount = 1.0f;
        const size_t bulgeChanged =
            CountDifferences(gridBaseline, harness.Render(shaped, grid, kOut, kOut));

        shaped.filters.distortion.amount = -1.0f;
        const size_t pinchChanged =
            CountDifferences(gridBaseline, harness.Render(shaped, grid, kOut, kOut));

        std::printf("  %-12s +1.00 moved %6zu px, -1.00 moved %6zu px of %zu\n", names[i],
                    bulgeChanged, pinchChanged, gridBaseline.pixels.size());

        CHECK(bulgeChanged > 5000);
        CHECK(pinchChanged > 5000);

        shaped.filters.distortion.amount = 0.0f;
        CHECK(CountDifferences(gridBaseline, harness.Render(shaped, grid, kOut, kOut)) == 0);
    }
}

// ADR-0010: no amount of distortion, in any shape, may open a transparent hole. Anti-fisheye
// reads from further out than the frame holds, so the old formula left a border - and wedges
// along the edges long before the extreme - where there was simply nothing to sample.
//
// Source and overlay share an aspect here, so a fully covered frame is the correct answer and
// any transparent pixel is the defect.
void TestDistortionNeverOpensAHole(Harness& harness) {
    const Image source = MakeGridSource(320, 240);
    constexpr uint32_t kOutW = 480;
    constexpr uint32_t kOutH = 360;

    const DistortionShape shapes[] = {DistortionShape::Radial, DistortionShape::Crt,
                                      DistortionShape::Cylindrical, DistortionShape::Vertical,
                                      DistortionShape::Corner};
    const char* names[] = {"radial", "crt", "cylindrical", "vertical", "corner"};
    const float amounts[] = {-1.0f, -0.75f, -0.5f, -0.25f, 0.25f, 0.5f, 0.75f, 1.0f};

    for (size_t i = 0; i < std::size(shapes); ++i) {
        for (const float amount : amounts) {
            AppSettings settings;
            settings.filters.distortion.enabled = true;
            settings.filters.distortion.shape = shapes[i];
            settings.filters.distortion.amount = amount;

            const Image rendered = harness.Render(settings, source, kOutW, kOutH);
            if (rendered.pixels.empty()) {
                CHECK(false);
                continue;
            }

            size_t holes = 0;
            for (const Rgba& pixel : rendered.pixels) {
                if (pixel.a != 255) {
                    ++holes;
                }
            }
            if (holes != 0) {
                std::printf("FAIL: %s at amount %+.2f left %zu transparent pixel(s) of %zu\n",
                            names[i], amount, holes, rendered.pixels.size());
                ++g_failures;
            }
        }
    }
}

// The two stages added by ADR-0009 that sample the source at extra points must not read outside
// the content: a bloom tap in the letterbox has no picture to bloom, and if it returned the
// clamped edge pixel the halo would leak into the bars.
void TestBloomDoesNotLeakIntoLetterbox(Harness& harness) {
    Image source = MakeEdgeSource(256, 64, 0.5f);
    // Make the right half maximally bright so there is as much to bloom as possible.
    for (auto& pixel : source.pixels) {
        if (pixel.g > 100) {
            pixel = Rgba{255, 255, 255, 255};
        }
    }
    constexpr uint32_t kOut = 400;

    AppSettings settings;
    settings.filters.bloom.enabled = true;
    settings.filters.bloom.intensity = 1.0f;
    settings.filters.bloom.threshold = 0.0f;
    settings.filters.bloom.radius = 1.0f;

    const Image rendered = harness.Render(settings, source, kOut, kOut);
    if (rendered.pixels.empty()) {
        CHECK(false);
        return;
    }

    // Just outside the content band, on the bright side.
    for (const uint32_t row : {120u, 140u, 262u, 280u}) {
        const Rgba& bar = rendered.At(300, row);
        if (bar.a != 0) {
            std::printf("FAIL: bloom leaked into the letterbox at row %u (alpha %u)\n", row, bar.a);
            ++g_failures;
        }
    }

    // And it did do something inside the picture.
    AppSettings off;
    const Image plain = harness.Render(off, source, kOut, kOut);
    CHECK(CountDifferences(plain, rendered) > 1000);
}

// A flat field has no detail, so an unsharp mask has nothing to sharpen and must be a no-op -
// everywhere, the last row of picture before the letterbox bar included. That edge is the whole
// point of the check: four of the five taps still land on the picture there but the fifth does
// not, and a mean taken without weighting by coverage would read that missing tap as black,
// push the high-pass positive and draw a bright rim around the content (ADR-0013, ADR-0011).
void TestSharpenDoesNotRimTheContentEdge(Harness& harness) {
    Image source;
    source.width = 128;
    source.height = 64;
    source.pixels.assign(static_cast<size_t>(source.width) * source.height,
                         Rgba{128, 128, 128, 255});
    constexpr uint32_t kOut = 400;

    AppSettings settings;
    settings.filters.sharpen.enabled = true;
    settings.filters.sharpen.intensity = 1.0f;
    settings.filters.sharpen.radius = 1.0f;

    const Image rendered = harness.Render(settings, source, kOut, kOut);
    const Image plain = harness.Render(AppSettings{}, source, kOut, kOut);
    if (rendered.pixels.empty() || plain.pixels.empty()) {
        CHECK(false);
        return;
    }

    int worst = 0;
    for (size_t i = 0; i < rendered.pixels.size(); ++i) {
        const Rgba& a = rendered.pixels[i];
        const Rgba& b = plain.pixels[i];
        worst = std::max(worst, std::abs(static_cast<int>(a.r) - static_cast<int>(b.r)));
        worst = std::max(worst, std::abs(static_cast<int>(a.g) - static_cast<int>(b.g)));
        worst = std::max(worst, std::abs(static_cast<int>(a.b) - static_cast<int>(b.b)));
    }

    // A couple of levels of tolerance for bilinear sampling, not the tens of levels a rim
    // would be worth.
    if (worst > 2) {
        std::printf("FAIL: sharpen altered a flat field by %d level(s); expected a no-op.\n",
                    worst);
        ++g_failures;
    }

    // And it does do something when there is detail to work on, so the check above is not
    // passing because the stage never ran.
    const Image edged = harness.Render(settings, MakeEdgeSource(128, 64, 0.5f), kOut, kOut);
    const Image edgedPlain = harness.Render(AppSettings{}, MakeEdgeSource(128, 64, 0.5f), kOut, kOut);
    CHECK(CountDifferences(edgedPlain, edged) > 100);
}

// --- Sample renderer ------------------------------------------------------------------------
//
// Not a test: a diagnostic mode that writes what the shader actually produces to disk, so a
// geometric claim can be looked at instead of argued about. Run with --write-samples <dir>.

int WriteSamples(Harness& harness, const char* directory) {
    const Image source = MakeGridSource(320, 240);
    constexpr uint32_t kOutW = 480;
    constexpr uint32_t kOutH = 360;
    const Rgba background{40, 40, 44, 255};

    struct Sample {
        const char* file;
        DistortionShape shape;
        float amount;
    };

    const Sample samples[] = {
        {"radial-neg100", DistortionShape::Radial, -1.00f},
        {"radial-neg050", DistortionShape::Radial, -0.50f},
        {"radial-000", DistortionShape::Radial, 0.00f},
        {"radial-pos050", DistortionShape::Radial, 0.50f},
        {"radial-pos100", DistortionShape::Radial, 1.00f},
        {"crt-pos100", DistortionShape::Crt, 1.00f},
        {"cylindrical-pos100", DistortionShape::Cylindrical, 1.00f},
        {"vertical-pos100", DistortionShape::Vertical, 1.00f},
        {"corner-pos100", DistortionShape::Corner, 1.00f},
        {"crt-neg100", DistortionShape::Crt, -1.00f},
    };

    int written = 0;

    {
        // The undistorted source, upscaled by the same path, as the reference.
        const AppSettings off;
        char path[512];
        std::snprintf(path, sizeof(path), "%s\\source.bmp", directory);
        if (WriteBmp(path, harness.Render(off, source, kOutW, kOutH), background)) {
            ++written;
        }
    }

    for (const Sample& sample : samples) {
        AppSettings settings;
        settings.filters.distortion.enabled = true;
        settings.filters.distortion.shape = sample.shape;
        settings.filters.distortion.amount = sample.amount;

        char path[512];
        std::snprintf(path, sizeof(path), "%s\\%s.bmp", directory, sample.file);
        if (WriteBmp(path, harness.Render(settings, source, kOutW, kOutH), background)) {
            ++written;
        }
    }

    std::printf("Wrote %d sample(s) to %s\n", written, directory);
    return written > 0 ? 0 : 1;
}

// Renders a built-in preset by name, so a look can be reviewed as an image rather than as a
// wall of parameter assignments. Unknown names are reported instead of silently skipped - a
// typo that quietly produced nothing would be worse than no tool at all.
int WritePresetSamples(Harness& harness, const char* directory, int count, char** names) {
    const Image source = MakeGridSource(320, 240);
    constexpr uint32_t kOutW = 480;
    constexpr uint32_t kOutH = 360;
    const Rgba background{40, 40, 44, 255};

    const std::vector<Preset> presets = BuiltInPresets();
    int written = 0;

    for (int i = 0; i < count; ++i) {
        const Preset* found = nullptr;
        for (const Preset& candidate : presets) {
            if (candidate.name == names[i]) {
                found = &candidate;
                break;
            }
        }
        if (found == nullptr) {
            std::printf("No built-in preset named '%s'\n", names[i]);
            continue;
        }

        AppSettings settings;
        settings.filters = found->filters;
        settings.effects = found->effects;

        // A fixed, non-zero time: the time-driven effects have to land somewhere, and picking
        // the same instant every run keeps the images comparable between builds.
        char path[512];
        std::snprintf(path, sizeof(path), "%s\\preset-%d.bmp", directory, i);
        if (WriteBmp(path, harness.Render(settings, source, kOutW, kOutH, 2.5f), background)) {
            ++written;
        }
    }

    std::printf("Wrote %d preset sample(s) to %s\n", written, directory);
    return written > 0 ? 0 : 1;
}


// The same idea as WritePresetSamples, but over a supplied frame and at that frame's own aspect
// ratio - which matters for anything whose shape is measured against the corners, the scope
// aperture above all. Output is named after the preset so a directory of these can be compared
// against the footage they are imitating.
int WritePresetSamplesFromImage(Harness& harness, const char* sourcePath, const char* directory,
                                int count, char** names) {
    Image source;
    if (!ReadBmp(sourcePath, source)) {
        return 1;
    }

    const Rgba background{40, 40, 44, 255};
    const std::vector<Preset> presets = BuiltInPresets();
    int written = 0;

    for (int i = 0; i < count; ++i) {
        const Preset* found = nullptr;
        for (const Preset& candidate : presets) {
            if (candidate.name == names[i]) {
                found = &candidate;
                break;
            }
        }
        if (found == nullptr) {
            std::printf("No built-in preset named '%s'\n", names[i]);
            continue;
        }

        AppSettings settings;
        settings.filters = found->filters;
        settings.effects = found->effects;

        char path[512];
        std::snprintf(path, sizeof(path), "%s\\%s.bmp", directory, names[i]);
        if (WriteBmp(path, harness.Render(settings, source, source.width, source.height, 2.5f),
                     background)) {
            ++written;
        }
    }

    std::printf("Wrote %d preset sample(s) to %s\n", written, directory);
    return written > 0 ? 0 : 1;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc >= 3 && std::strcmp(argv[1], "--write-samples") == 0) {
        Harness renderer;
        if (!renderer.Create()) {
            std::printf("Direct3D 11 unavailable; no samples written.\n");
            return 1;
        }
        return WriteSamples(renderer, argv[2]);
    }

    if (argc >= 4 && std::strcmp(argv[1], "--write-presets") == 0) {
        Harness renderer;
        if (!renderer.Create()) {
            std::printf("Direct3D 11 unavailable; no samples written.\n");
            return 1;
        }
        return WritePresetSamples(renderer, argv[2], argc - 3, argv + 3);
    }

    if (argc >= 5 && std::strcmp(argv[1], "--write-presets-from") == 0) {
        Harness renderer;
        if (!renderer.Create()) {
            std::printf("Direct3D 11 unavailable; no samples written.\n");
            return 1;
        }
        return WritePresetSamplesFromImage(renderer, argv[2], argv[3], argc - 4, argv + 4);
    }

    Harness harness;
    if (!harness.Create()) {
        // Not a failure: without a Direct3D 11 device there is nothing to measure, and the
        // remaining suites still have to be able to run.
        std::printf("Direct3D 11 unavailable; shader pipeline tests skipped.\n");
        return 0;
    }

    TestDisabledModulesAreFree(harness);
    TestAspectFitLetterbox(harness);
    TestMatchingAspectFillsOverlay(harness);
    TestDistortionMovesTheImage(harness);
    TestDistortionNeverOpensAHole(harness);
    TestBloomDoesNotLeakIntoLetterbox(harness);
    TestSharpenDoesNotRimTheContentEdge(harness);

    if (g_failures == 0) {
        std::printf("All shader pipeline tests passed.\n");
        return 0;
    }
    std::printf("%d check(s) failed.\n", g_failures);
    return 1;
}
