#include "graphics/ShaderManager.h"

#include <Windows.h>

#include "util/Log.h"
#include "util/Win32Helpers.h"

// Generated by cmake/CompileShaders.cmake at build time.
#include "shaders/OverlayDeskPS.h"
#include "shaders/OverlayDeskVS.h"

#if defined(_DEBUG)
#include <d3dcompiler.h>
#endif

namespace overlaydesk {

void ShaderManager::CreateFromEmbedded(ID3D11Device* device) {
    com_ptr<ID3D11VertexShader> vertexShader;
    com_ptr<ID3D11PixelShader> pixelShader;

    OS_CHECK_HR(device->CreateVertexShader(g_OverlayDeskVS, sizeof(g_OverlayDeskVS), nullptr,
                                           vertexShader.put()));
    OS_CHECK_HR(device->CreatePixelShader(g_OverlayDeskPS, sizeof(g_OverlayDeskPS), nullptr,
                                          pixelShader.put()));

    m_vertexShader = std::move(vertexShader);
    m_pixelShader = std::move(pixelShader);
    ++m_generation;

    LogInfo("Shaders: embedded bytecode loaded (vs {} bytes, ps {} bytes).",
            sizeof(g_OverlayDeskVS), sizeof(g_OverlayDeskPS));
}

void ShaderManager::Reset() noexcept {
    m_pixelShader = nullptr;
    m_vertexShader = nullptr;
}

std::filesystem::path ShaderManager::DefaultSourceDirectory() {
#if defined(OVERLAYDESK_SHADER_SOURCE_DIR)
    return std::filesystem::path(OVERLAYDESK_SHADER_SOURCE_DIR);
#else
    return {};
#endif
}

bool ShaderManager::HotReloadSupported() noexcept {
#if defined(_DEBUG)
    return true;
#else
    return false;
#endif
}

#if defined(_DEBUG)

namespace {

// A minimal include handler so Common.hlsli resolves relative to the shader directory.
class ShaderIncludeHandler final : public ID3DInclude {
public:
    explicit ShaderIncludeHandler(std::filesystem::path directory)
        : m_directory(std::move(directory)) {}

    HRESULT __stdcall Open(D3D_INCLUDE_TYPE, LPCSTR fileName, LPCVOID, LPCVOID* data,
                           UINT* bytes) override {
        try {
            const std::filesystem::path path = m_directory / fileName;
            std::FILE* file = nullptr;
            if (_wfopen_s(&file, path.c_str(), L"rb") != 0 || file == nullptr) {
                return E_FAIL;
            }

            std::fseek(file, 0, SEEK_END);
            const long size = std::ftell(file);
            std::fseek(file, 0, SEEK_SET);
            if (size <= 0) {
                std::fclose(file);
                return E_FAIL;
            }

            auto* buffer = new char[static_cast<size_t>(size)];
            const size_t read = std::fread(buffer, 1, static_cast<size_t>(size), file);
            std::fclose(file);

            *data = buffer;
            *bytes = static_cast<UINT>(read);
            return S_OK;
        } catch (...) {
            return E_FAIL;
        }
    }

    HRESULT __stdcall Close(LPCVOID data) override {
        delete[] static_cast<const char*>(data);
        return S_OK;
    }

private:
    std::filesystem::path m_directory;
};

bool CompileStage(const std::filesystem::path& file, const char* profile,
                  ShaderIncludeHandler& includeHandler, com_ptr<ID3DBlob>& blobOut,
                  std::string& errorOut) {
    com_ptr<ID3DBlob> errors;
    const HRESULT hr = ::D3DCompileFromFile(file.c_str(), nullptr, &includeHandler, "main", profile,
                                            D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION |
                                                D3DCOMPILE_WARNINGS_ARE_ERRORS,
                                            0, blobOut.put(), errors.put());
    if (FAILED(hr)) {
        errorOut = errors ? std::string(static_cast<const char*>(errors->GetBufferPointer()),
                                        errors->GetBufferSize())
                          : std::format("D3DCompileFromFile failed: 0x{:08X}",
                                        static_cast<uint32_t>(hr));
        return false;
    }
    return true;
}

}  // namespace

bool ShaderManager::ReloadFromSource(ID3D11Device* device,
                                     const std::filesystem::path& shaderDirectory,
                                     std::string& errorOut) {
    errorOut.clear();

    if (device == nullptr || shaderDirectory.empty() ||
        !std::filesystem::exists(shaderDirectory / L"OverlayDeskPS.hlsl")) {
        errorOut = "Shader sources not found next to the build; hot reload unavailable.";
        return false;
    }

    ShaderIncludeHandler includeHandler(shaderDirectory);

    com_ptr<ID3DBlob> vsBlob;
    if (!CompileStage(shaderDirectory / L"OverlayDeskVS.hlsl", "vs_5_0", includeHandler, vsBlob,
                      errorOut)) {
        LogError("Shaders: vertex stage reload failed: {}", errorOut);
        return false;
    }

    com_ptr<ID3DBlob> psBlob;
    if (!CompileStage(shaderDirectory / L"OverlayDeskPS.hlsl", "ps_5_0", includeHandler, psBlob,
                      errorOut)) {
        LogError("Shaders: pixel stage reload failed: {}", errorOut);
        return false;
    }

    // Build both objects before swapping either in, so a half-successful reload cannot
    // leave the renderer with a mismatched pair.
    com_ptr<ID3D11VertexShader> vertexShader;
    com_ptr<ID3D11PixelShader> pixelShader;
    HRESULT hr = device->CreateVertexShader(vsBlob->GetBufferPointer(), vsBlob->GetBufferSize(),
                                            nullptr, vertexShader.put());
    if (SUCCEEDED(hr)) {
        hr = device->CreatePixelShader(psBlob->GetBufferPointer(), psBlob->GetBufferSize(), nullptr,
                                       pixelShader.put());
    }
    if (FAILED(hr)) {
        errorOut = std::format("Creating the reloaded shaders failed: 0x{:08X}",
                               static_cast<uint32_t>(hr));
        LogError("Shaders: {}", errorOut);
        return false;
    }

    m_vertexShader = std::move(vertexShader);
    m_pixelShader = std::move(pixelShader);
    ++m_generation;

    LogInfo("Shaders: hot reloaded from {} (generation {}).",
            Utf8FromWide(shaderDirectory.wstring()), m_generation);
    return true;
}

#else  // !_DEBUG

bool ShaderManager::ReloadFromSource(ID3D11Device*, const std::filesystem::path&,
                                     std::string& errorOut) {
    errorOut = "Shader hot reload is a Debug-build feature.";
    return false;
}

#endif  // _DEBUG

}  // namespace overlaydesk
