# CompileShaders.cmake
#
# Compiles HLSL to embedded bytecode headers with fxc.exe at build time.
#
# ADR-0005 / PERFORMANCE.md: shaders must never be compiled in the hot path, and the
# release executable should not depend on loose .hlsl files on disk. fxc emits a C header
# (/Fh) holding a byte array (/Vn), which we compile straight into the binary.
#
# ShaderManager can still recompile from source at runtime in Debug builds (hot reload).

find_program(FXC_EXECUTABLE
    NAMES fxc
    HINTS
        "${WINDOWS_KITS_ROOT}/bin/${OVERLAYDESK_SDK_VERSION}/x64"
        "${WINDOWS_KITS_ROOT}/bin/x64"
    DOC "Path to the DirectX shader compiler (fxc.exe) from the Windows SDK")

if(NOT FXC_EXECUTABLE)
    message(FATAL_ERROR
        "fxc.exe was not found. Install the Windows SDK component 'Windows SDK for Desktop C++'. "
        "Looked under: ${WINDOWS_KITS_ROOT}/bin/${OVERLAYDESK_SDK_VERSION}/x64")
endif()

message(STATUS "fxc.exe: ${FXC_EXECUTABLE}")

# add_hlsl_shader(<target>
#     SOURCE   <path to .hlsl>
#     PROFILE  <e.g. ps_5_0>
#     ENTRY    <entry point>
#     VARIABLE <name of the generated byte array>
#     [DEPENDS <extra files>...])
function(add_hlsl_shader TARGET_NAME)
    cmake_parse_arguments(ARG "" "SOURCE;PROFILE;ENTRY;VARIABLE" "DEPENDS" ${ARGN})

    get_filename_component(SHADER_NAME "${ARG_SOURCE}" NAME_WE)
    set(GENERATED_ROOT "${CMAKE_BINARY_DIR}/generated/$<CONFIG>")
    set(OUTPUT_HEADER "${GENERATED_ROOT}/shaders/${SHADER_NAME}.h")

    # One $<IF:> producing a ";"-list, expanded by COMMAND_EXPAND_LISTS. Per-flag
    # $<$<CONFIG:Debug>:/Zi> expressions would each leave an empty argument behind in the
    # configuration where they do not apply, and fxc treats an empty argument as an extra
    # input file and fails with no diagnostic at all.
    set(CONFIG_FLAGS "$<IF:$<CONFIG:Debug>,/Zi;/Od,/O3;/Qstrip_reflect;/Qstrip_debug>")

    add_custom_command(
        OUTPUT "${OUTPUT_HEADER}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${GENERATED_ROOT}/shaders"
        COMMAND "${FXC_EXECUTABLE}"
                /nologo
                /T ${ARG_PROFILE}
                /E ${ARG_ENTRY}
                /Vn ${ARG_VARIABLE}
                /Fh "${OUTPUT_HEADER}"
                /WX
                "${CONFIG_FLAGS}"
                "${ARG_SOURCE}"
        MAIN_DEPENDENCY "${ARG_SOURCE}"
        DEPENDS ${ARG_DEPENDS}
        COMMENT "fxc ${ARG_PROFILE} ${SHADER_NAME}.hlsl -> ${SHADER_NAME}.h"
        COMMAND_EXPAND_LISTS
        VERBATIM)

    target_sources(${TARGET_NAME} PRIVATE "${ARG_SOURCE}" "${OUTPUT_HEADER}")
    target_include_directories(${TARGET_NAME} PRIVATE "${GENERATED_ROOT}")

    # Keep the .hlsl visible in the IDE but out of the C++ compiler's hands.
    set_source_files_properties("${ARG_SOURCE}" PROPERTIES HEADER_FILE_ONLY TRUE)
    source_group("Shaders" FILES "${ARG_SOURCE}")
    source_group("Shaders/Generated" FILES "${OUTPUT_HEADER}")
endfunction()
